### PR TITLE
Allow to set own event_type and changed how default one is computed

### PR DESCRIPTION
**Pull request by lukaszb**

### CODE REVIEW

**Comment by renou** [comment]
what is this for?

**Comment by fala** [comment]
Why can't we rely on the `aggregate_type` and `event_type` in handlers? If I understand well, now we'll have redundancy in form of `<aggregate_type>_<event_type>`.

**Comment by lukaszb** [comment]
@fala this is exactly my concern. I'm checking how java framework handle this. It might end up that it would suffice to allow to override event type at the `DomainEvent` class (part related with attribute) - in that case I would rollback some changes.

**Comment by piotrekno1** [comment]
@renou We want to enable: https://myutest.jira.com/browse/DX-1404

What do you think?

**Comment by renou** [comment]
Thanks for the effort to improve the lib! but I think this will break the event data consistence with java services, since java services only saves event name instead of aggreate_event_name in the event type column. And we will be saving duplicated info, aggregate type, twice into the event journal. I have the same question as @fala, can we make the handler smarter and use aggregate_type and event_type?

**Comment by renou** [comment]
After talking with @piotrekno1, it looks like a data format inconsistency between java and python lib.
In java, the event type is <aggregate_type>_<event_type>, such as "project_activation_requested". [this code?](https://github.com/ApplauseAQI/axon-common-java/blob/8cef6b493c937af11e17e69ac5b074ca2188c42f/src/main/java/com/applause/axon/eventstore/jdbc/DomainEventStorageEngine.java#L158).

Feels like a java side fix to remove the duplicated aggregate type prefix.

**Comment by lukaszb** [comment]
Ok, so some changes here needs to be removed, namely part which prefixes event_type with aggregate type. Going to fix that on Monday as I am off tomorrow.

**Comment by michalno1** [comment]
@renou This is no longer true and we did't know about the convention. We have events like TasksReorderedInJourney (event_type: 'tasks_reordered_in_journey') where a Task is not an aggregate. We have an event BuildRegisteredWithProject where build is neither an aggregate nor an entity from project-svc perspective. We tried to construct the event names/types so that a non-coder could still have a pretty good idea of what it did.

**Comment by narfdotpl** [comment]
Just a reminder that this thread is publicly visible — repository is open-sourced.

I'll continue the discussion [on JIRA](https://myutest.jira.com/browse/DX-1404).

**Comment by renou** [comment]
@michalno1  I see, I see. So it's not a framework difference, rather a convention difference. I guess, in this case, we only need to change python's camel case to snake case. @lukaszb

**Pull request merged**
