### PR TITLE
optional event journal partition

### PR DESCRIPTION
**Pull request by renou**
Since the event journal table could grow rapidly, we should partition the table to improve performance. This migration partition the table by aggregate type.

### CODE REVIEW

**Comment by renou** [comment]
@lukaszb @piotrekno1 Please review. Basically, we want table be partitioned when created in production environment. I'm not 100% sure if I should include this or let library users define the DB schema themselves.

**Comment by lukaszb** [comment]
Let's summarise requirements for this:

- it should be configurable (partitions number)
- it should be reversible (so for migration there should be backward step too, otherwise replaying migrations would fail)
- it should work for all databases (mysql, postgresql, sqlite) or fail with proper message (it might be a good moment to tweak travis configuration)
- it should be tested (at least drop `--nomigrations` from `tox.ini` config)

I am not sure if migration is best fit here - it might get complicated if we introduce a migration in future (I know there is a small chance for that but who knows) it would be hard to reverse migrations and run them only to get partitioning. A management command might be a better call here.

**Comment by piotrekno1** [comment]
@renou +1 to the management command approach.

Do you think that an interface like that would be enough:

```python
./manage.py partition_event_journal  -p N  
```

? N = amount of partitions.

I am not sure ATM what kind of policies & limits there should be in place for N though.

**Comment by renou** [comment]
@piotrekno1 @lukaszb very good points! Thank you guys!
I like the management command approach too because of its flexibility. Supporting different DBs too.

**Comment by renou** [comment]
close this for now, need more investigation.

**Pull request closed without merging**
